### ISSUE TITLE
Simulate don't work

### ISSUE THREAD

**Issue by EngineerForce** [pizzapi2012/Fritzing-Prebuilt-Release-For-Windows#3]
Hi, 

Fritzing fatal crash after click simulate button, are there other dependencies than C++ runtime?

**Comment by pizzapi2012** [comment]
![image](https://github.com/pizzapi2012/Fritzing-Prebuilt-Release-For-Windows/assets/157081760/9d45dbf3-f1e3-42f1-bffa-3c516f8d314f)
this error?

**Comment by pizzapi2012** [comment]
same as https://github.com/FREEWING-JP/Build-Fritzing-1.0.0-Windows-script/issues/16

**Comment by EngineerForce** [comment]
Yes, in meantime I found out that the ngspice.dll is not in the package. Adding them rise an waning that simulation currently not working

**Comment by pizzapi2012** [comment]
you just need the nspice dll

**Comment by pizzapi2012** [comment]
(i added the nspice dll to the package)

**Comment by pizzapi2012** [comment]
> Yes, in meantime I found out that the ngspice.dll is not in the package. Adding them rise an waning that simulation currently not working

can you star this repo?
